# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui',
# licensing of 'Ui_MainWindow.ui' applies.
#
# Created: Mon Jan 14 20:42:56 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_WeldLegWidth = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_WeldLegWidth.setObjectName("label_WeldLegWidth")
        self.gridLayout.addWidget(self.label_WeldLegWidth, 1, 0, 1, 1)
        self.lineEdit_Index = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Index.setObjectName("lineEdit_Index")
        self.gridLayout.addWidget(self.lineEdit_Index, 0, 2, 1, 1)
        self.lineEdit_GrooveGap = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_GrooveGap.setObjectName("lineEdit_GrooveGap")
        self.gridLayout.addWidget(self.lineEdit_GrooveGap, 2, 2, 1, 1)
        self.label_SeamCenterX = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_SeamCenterX.setObjectName("label_SeamCenterX")
        self.gridLayout.addWidget(self.label_SeamCenterX, 5, 0, 1, 1)
        self.label_GrooveGap = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_GrooveGap.setObjectName("label_GrooveGap")
        self.gridLayout.addWidget(self.label_GrooveGap, 2, 0, 1, 1)
        self.label_BranchGrooveRoot = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_BranchGrooveRoot.setObjectName("label_BranchGrooveRoot")
        self.gridLayout.addWidget(self.label_BranchGrooveRoot, 3, 0, 1, 1)
        self.lineEdit_BranchGrooveRoot = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_BranchGrooveRoot.setObjectName("lineEdit_BranchGrooveRoot")
        self.gridLayout.addWidget(self.lineEdit_BranchGrooveRoot, 3, 2, 1, 1)
        self.lineEdit_BranchGrooveAngle = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_BranchGrooveAngle.setObjectName("lineEdit_BranchGrooveAngle")
        self.gridLayout.addWidget(self.lineEdit_BranchGrooveAngle, 4, 2, 1, 1)
        self.lineEdit_SeamCenterX = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_SeamCenterX.setObjectName("lineEdit_SeamCenterX")
        self.gridLayout.addWidget(self.lineEdit_SeamCenterX, 5, 2, 1, 1)
        self.lineEdit_WeldLegWidth = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_WeldLegWidth.setObjectName("lineEdit_WeldLegWidth")
        self.gridLayout.addWidget(self.lineEdit_WeldLegWidth, 1, 2, 1, 1)
        self.label_BranchGrooveAngle = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_BranchGrooveAngle.setObjectName("label_BranchGrooveAngle")
        self.gridLayout.addWidget(self.label_BranchGrooveAngle, 4, 0, 1, 1)
        self.label_Index = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Index.setObjectName("label_Index")
        self.gridLayout.addWidget(self.label_Index, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.lineEdit_SeamNormalAngle = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_SeamNormalAngle.setObjectName("lineEdit_SeamNormalAngle")
        self.gridLayout.addWidget(self.lineEdit_SeamNormalAngle, 6, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Controller = QtWidgets.QMenu(self.menubar)
        self.menu_Controller.setObjectName("menu_Controller")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_AddController = QtWidgets.QAction(MainWindow)
        self.action_AddController.setObjectName("action_AddController")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_View_statusbar = QtWidgets.QAction(MainWindow)
        self.action_View_statusbar.setCheckable(True)
        self.action_View_statusbar.setChecked(True)
        self.action_View_statusbar.setObjectName("action_View_statusbar")
        self.menu_Controller.addAction(self.action_AddController)
        self.menu_Controller.addAction(self.action_Exit)
        self.menu_View.addAction(self.action_View_statusbar)
        self.menubar.addAction(self.menu_Controller.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.toolBar.addAction(self.action_AddController)
        self.toolBar.addAction(self.action_Exit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_WeldLegWidth.setText(QtWidgets.QApplication.translate("MainWindow", "WeldLegWidth", None, -1))
        self.label_SeamCenterX.setText(QtWidgets.QApplication.translate("MainWindow", "SeamCenterX", None, -1))
        self.label_GrooveGap.setText(QtWidgets.QApplication.translate("MainWindow", "GrooveGap", None, -1))
        self.label_BranchGrooveRoot.setText(QtWidgets.QApplication.translate("MainWindow", "BranchGrooveRoot", None, -1))
        self.label_BranchGrooveAngle.setText(QtWidgets.QApplication.translate("MainWindow", "BranchGrooveAngle", None, -1))
        self.label_Index.setText(QtWidgets.QApplication.translate("MainWindow", "Index", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "SeamNormalAngle", None, -1))
        self.menu_Controller.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Controller", None, -1))
        self.menu_View.setTitle(QtWidgets.QApplication.translate("MainWindow", "&View", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.action_AddController.setText(QtWidgets.QApplication.translate("MainWindow", "&Add Controller", None, -1))
        self.action_AddController.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+A", None, -1))
        self.action_Exit.setText(QtWidgets.QApplication.translate("MainWindow", "&Exit", None, -1))
        self.action_Exit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Exit application", None, -1))
        self.action_Exit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.action_View_statusbar.setText(QtWidgets.QApplication.translate("MainWindow", "View statusbar", None, -1))
        self.action_View_statusbar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "View statusbar", None, -1))

